##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|devnet|testnet-2]
log_level: debug # [debug|info]

external_api:
  endpoints:
    coingecko: "https://api.coingecko.com/api/v3/"
    ens: "https://api.thegraph.com/subgraphs/name/ensdomains/ens"

mainnet:
  endpoints:
    rpc: "http://rpc.axelarscan.io:26657"
    lcd: "http://rpc.axelarscan.io:1317"
    cli: "http://rpc.axelarscan.io:3333"
    api: "https://api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15

testnet:
  endpoints:
    rpc: "http://testnet.rpc.axelarscan.io:26657"
    lcd: "http://testnet.rpc.axelarscan.io:1317"
    cli: "http://testnet.rpc.axelarscan.io:3333"
    api: "https://testnet.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15

devnet:
  endpoints:
    rpc: "http://devnet.rpc.axelarscan.io:26657"
    lcd: "http://devnet.rpc.axelarscan.io:1317"
    cli: "http://devnet.rpc.axelarscan.io:3333"
    api: "https://devnet.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15

testnet-2:
  endpoints:
    rpc: "http://testnet-2.rpc.axelarscan.io:26657"
    lcd: "http://testnet-2.rpc.axelarscan.io:1317"
    cli: "http://testnet-2.rpc.axelarscan.io:3333"
    api: "https://testnet-2.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15