##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|devnet|testnet-2]
log_level: debug # [debug|info]

external_api:
  endpoints:
    coingecko: "https://api.coingecko.com/api/v3/"
    ens: "https://api.thegraph.com/subgraphs/name/ensdomains/ens"

mainnet:
  endpoints:
    rpc: "http://rpc.axelarscan.io:26657"
    lcd: "http://rpc.axelarscan.io:1317"
    cli: "http://rpc.axelarscan.io:3333"
    api: "https://api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15
  percent_diff_supply_threshold: 2
  gateway:
    chains:
      ethereum:
        endpoints:
          rpc:
            - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
        native_token:
          name: "Ethereum"
          symbol: "ETH"
          decimals: 18
      binance:
        endpoints:
          rpc:
            - "https://rpc.ankr.com/bsc"
        native_token:
          name: "BNB"
          symbol: "BNB"
          decimals: 18
      avalanche:
        endpoints:
          rpc:
            - "https://rpc.ankr.com/avalanche"
        native_token:
          name: "Avalanche"
          symbol: "AVAX"
          decimals: 18
      polygon:
        endpoints:
          rpc:
            - "https://rpc.ankr.com/polygon"
        native_token:
          name: "Polygon"
          symbol: "MATIC"
          decimals: 18
      fantom:
        endpoints:
          rpc:
            - "https://rpc.ankr.com/fantom"
        native_token:
          name: "Fantom"
          symbol: "FTM"
          decimals: 18
      moonbeam:
        endpoints:
          rpc:
            - "https://rpc.ankr.com/moonbeam"
        native_token:
          name: "Moonbeam"
          symbol: "GLMR"
          decimals: 18
      aurora:
        endpoints:
          rpc:
            - "https://mainnet.aurora.dev"
        native_token:
          name: "Ethereum"
          symbol: "ETH"
          decimals: 18
    contracts:
      ethereum:
        address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
      binance:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      avalanche:
        address: "0x5029C0EFf6C34351a0CEc334542cDb22c7928f78"
      polygon:
        address: "0x6f015F16De9fC8791b234eF68D486d2bF203FBA8"
      fantom:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
      moonbeam:
        address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
      aurora:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"

testnet:
  endpoints:
    rpc: "http://testnet.rpc.axelarscan.io:26657"
    lcd: "http://testnet.rpc.axelarscan.io:1317"
    cli: "http://testnet.rpc.axelarscan.io:3333"
    api: "https://testnet.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15
  percent_diff_supply_threshold: 2
  gateway:
    chains:
      ethereum:
        endpoints:
          rpc:
            - "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
        native_token:
          name: "Ethereum"
          symbol: "ETH"
          decimals: 18
      binance:
        endpoints:
          rpc:
            - "https://data-seed-prebsc-1-s1.binance.org:8545"
        native_token:
          name: "BNB"
          symbol: "BNB"
          decimals: 18
      avalanche:
        endpoints:
          rpc:
            - "https://api.avax-test.network/ext/bc/C/rpc"
        native_token:
          name: "Avalanche"
          symbol: "AVAX"
          decimals: 18
      polygon:
        endpoints:
          rpc:
            - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
        native_token:
          name: "Matic"
          symbol: "MATIC"
          decimals: 18
      fantom:
        endpoints:
          rpc:
            - "https://rpc.testnet.fantom.network"
            - "https://xapi.testnet.fantom.network/lachesis"
        native_token:
          name: "Fantom"
          symbol: "FTM"
          decimals: 18
      moonbeam:
        endpoints:
          rpc:
            - "https://rpc.api.moonbase.moonbeam.network"
        native_token:
          name: "Dev"
          symbol: "DEV"
          decimals: 18
      aurora:
        endpoints:
          rpc:
            - "https://testnet.aurora.dev"
        native_token:
          name: "Ethereum"
          symbol: "ETH"
          decimals: 18
    contracts:
      ethereum:
        address: "0xBC6fcce7c5487d43830a219CA6E7B83238B41e71"
      binance:
        address: "0x4D147dCb984e6affEEC47e44293DA442580A3Ec0"
      avalanche:
        address: "0xC249632c2D40b9001FE907806902f63038B737Ab"
      polygon:
        address: "0xBF62ef1486468a6bd26Dd669C06db43dEd5B849B"
      fantom:
        address: "0x97837985Ec0494E7b9C71f5D3f9250188477ae14"
      moonbeam:
        address: "0x5769D84DD62a6fD969856c75c7D321b84d455929"
      aurora:
        address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"

devnet:
  endpoints:
    rpc: "http://devnet.rpc.axelarscan.io:26657"
    lcd: "http://devnet.rpc.axelarscan.io:1317"
    cli: "http://devnet.rpc.axelarscan.io:3333"
    api: "https://devnet.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15

testnet-2:
  endpoints:
    rpc: "http://testnet-2.rpc.axelarscan.io:26657"
    lcd: "http://testnet-2.rpc.axelarscan.io:1317"
    cli: "http://testnet-2.rpc.axelarscan.io:3333"
    api: "https://testnet-2.api.axelarscan.io"
  num_blocks_avg_block_time: 100
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  store_blocks: 100000
  cache_timeout_minutes: 15