##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|devnet]
log_level: debug # [debug|info]

mainnet:
  endpoints:
    api: "https://api.axelarscan.io"
  avg_block_time_ms: 6000
  snapshot_block_size: 10000
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  max_miss: 17500

testnet:
  endpoints:
    api: "https://testnet.api.axelarscan.io"
  avg_block_time_ms: 6000
  snapshot_block_size: 10000
  num_blocks_per_heartbeat: 50
  fraction_heartbeat_block: 1
  max_miss: 17500
