##################################
# RPCs & Contracts Configuration #
##################################

mainnet:
  api: "https://api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum:
      endpoints:
        rpc:
          - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/eth"
      native_token:
        name: "Ethereum"
        symbol: "ETH"
        decimals: 18
    binance:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/bsc"
          - "https://bsc-dataseed.binance.org"
      native_token:
        name: "BNB"
        symbol: "BNB"
        decimals: 18
    avalanche:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/avalanche"
          - "https://api.avax.network/ext/bc/C/rpc"
      native_token:
        name: "Avalanche"
        symbol: "AVAX"
        decimals: 18
    polygon:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/polygon"
      native_token:
        name: "Polygon"
        symbol: "MATIC"
        decimals: 18
    fantom:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/fantom"
          - "https://rpc.ftm.tools"
          - "https://rpcapi.fantom.network"
      native_token:
        name: "Fantom"
        symbol: "FTM"
        decimals: 18
    moonbeam:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/moonbeam"
          - "https://rpc.api.moonbeam.network"
      native_token:
        name: "Moonbeam"
        symbol: "GLMR"
        decimals: 18
    aurora:
      endpoints:
        rpc:
          - "https://mainnet.aurora.dev"
      native_token:
        name: "Ethereum"
        symbol: "ETH"
        decimals: 18
  gateway_contracts:
    ethereum:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    binance:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    avalanche:
      address: "0x5029C0EFf6C34351a0CEc334542cDb22c7928f78"
    polygon:
      address: "0x6f015F16De9fC8791b234eF68D486d2bF203FBA8"
    fantom:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    moonbeam:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"



testnet:
  api: "https://testnet.api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum:
      endpoints:
        rpc:
          - "https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
      native_token:
        name: "Ethereum"
        symbol: "ETH"
        decimals: 18
    binance:
      endpoints:
        rpc:
          - "https://data-seed-prebsc-1-s1.binance.org:8545"
          - "https://data-seed-prebsc-2-s1.binance.org:8545"
          - "https://data-seed-prebsc-1-s2.binance.org:8545"
      native_token:
        name: "BNB"
        symbol: "BNB"
        decimals: 18
    avalanche:
      endpoints:
        rpc:
          - "https://api.avax-test.network/ext/bc/C/rpc"
      native_token:
        name: "Avalanche"
        symbol: "AVAX"
        decimals: 18
    polygon:
      endpoints:
        rpc:
          - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://matic-mumbai.chainstacklabs.com"
      native_token:
        name: "Polygon"
        symbol: "MATIC"
        decimals: 18
    fantom:
      endpoints:
        rpc:
          - "https://rpc.testnet.fantom.network"
          - "https://xapi.testnet.fantom.network/lachesis"
      native_token:
        name: "Fantom"
        symbol: "FTM"
        decimals: 18
    moonbeam:
      endpoints:
        rpc:
          - "https://rpc.api.moonbase.moonbeam.network"
      native_token:
        name: "Dev"
        symbol: "DEV"
        decimals: 18
    aurora:
      endpoints:
        rpc:
          - "https://testnet.aurora.dev"
      native_token:
        name: "Ethereum"
        symbol: "ETH"
        decimals: 18
  gateway_contracts:
    ethereum:
      address: "0xBC6fcce7c5487d43830a219CA6E7B83238B41e71"
    binance:
      address: "0x4D147dCb984e6affEEC47e44293DA442580A3Ec0"
    avalanche:
      address: "0xC249632c2D40b9001FE907806902f63038B737Ab"
    polygon:
      address: "0xBF62ef1486468a6bd26Dd669C06db43dEd5B849B"
    fantom:
      address: "0x97837985Ec0494E7b9C71f5D3f9250188477ae14"
    moonbeam:
      address: "0x5769D84DD62a6fD969856c75c7D321b84d455929"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"