##################################
# RPCs & Contracts Configuration #
##################################

mainnet:
  api: "https://api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum:
      endpoints:
        rpc:
          - "https://mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/eth"
    binance:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/bsc"
          - "https://bscrpc.com"
    polygon:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/polygon"
          - "https://matic-mainnet.chainstacklabs.com"
          - "https://polygon-rpc.com"
    avalanche:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/avalanche"
          - "https://api.avax.network/ext/bc/C/rpc"
    fantom:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/fantom"
          - "https://rpc.ftm.tools"
    moonbeam:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/moonbeam"
          - "https://rpc.api.moonbeam.network"
    aurora:
      endpoints:
        rpc:
          - "https://mainnet.aurora.dev"
    arbitrum:
      endpoints:
        rpc:
          - "https://arbitrum-mainnet.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/arbitrum"
          - "https://arb1.arbitrum.io/rpc"
    optimism:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/optimism"
          - "https://mainnet.optimism.io"
    celo:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/celo"
          - "https://forno.celo.org"
    kava:
      endpoints:
        rpc:
          - "https://evm.kava.io"
          - "https://evm2.kava.io"
  gateway_contracts:
    ethereum:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    binance:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    avalanche:
      address: "0x5029C0EFf6C34351a0CEc334542cDb22c7928f78"
    polygon:
      address: "0x6f015F16De9fC8791b234eF68D486d2bF203FBA8"
    fantom:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    moonbeam:
      address: "0x4F4495243837681061C4743b74B3eEdf548D56A5"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    arbitrum:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    optimism:
      address: ""
    celo:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    kava:
      address: ""



testnet:
  api: "https://testnet.api.axelarscan.io"
  past_events_block_per_request: 100 # [1-500]
  chains:
    ethereum-2:
      endpoints:
        rpc:
          - "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/eth_goerli"
    binance:
      endpoints:
        rpc:
          - "https://data-seed-prebsc-1-s1.binance.org:8545"
          - "https://data-seed-prebsc-2-s1.binance.org:8545"
          - "https://data-seed-prebsc-1-s2.binance.org:8545"
    polygon:
      endpoints:
        rpc:
          - "https://polygon-mumbai.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
          - "https://rpc.ankr.com/polygon_mumbai"
          - "https://matic-mumbai.chainstacklabs.com"
    avalanche:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/avalanche_fuji"
          - "https://api.avax-test.network/ext/bc/C/rpc"
    fantom:
      endpoints:
        rpc:
          - "https://rpc.ankr.com/fantom_testnet"
          - "https://rpc.testnet.fantom.network"
    moonbeam:
      endpoints:
        rpc:
          - "https://rpc.api.moonbase.moonbeam.network"
          - "https://rpc.testnet.moonbeam.network"
    aurora:
      endpoints:
        rpc:
          - "https://testnet.aurora.dev"
    arbitrum:
      endpoints:
        rpc:
          - "https://goerli-rollup.arbitrum.io/rpc"
    optimism:
      endpoints:
        rpc:
          - "https://goerli.optimism.io"
    celo:
      endpoints:
        rpc:
          - "https://alfajores-forno.celo-testnet.org"
    kava:
      endpoints:
        rpc:
          - "https://evm.testnet.kava.io"
  gateway_contracts:
    ethereum-2:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    binance:
      address: "0x4D147dCb984e6affEEC47e44293DA442580A3Ec0"
    avalanche:
      address: "0xC249632c2D40b9001FE907806902f63038B737Ab"
    polygon:
      address: "0xBF62ef1486468a6bd26Dd669C06db43dEd5B849B"
    fantom:
      address: "0x97837985Ec0494E7b9C71f5D3f9250188477ae14"
    moonbeam:
      address: "0x5769D84DD62a6fD969856c75c7D321b84d455929"
    aurora:
      address: "0x304acf330bbE08d1e512eefaa92F6a57871fD895"
    arbitrum:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    optimism:
      address: ""
    celo:
      address: "0xe432150cce91c13a887f7D836923d5597adD8E31"
    kava:
      address: "0xC8D18F85cB0Cee5C95eC29c69DeaF6cea972349c"