##########################
# Services Configuration #
##########################

environment: testnet # [testnet|mainnet|devnet|testnet-2]
port:
  cli: 3333
log_level: debug # [debug|info]

mainnet:
  endpoints:
    ws: "ws://agent.axelarscan.io:26657"
    api: "https://api.axelarscan.io"
  num_prev_blocks_fetch_tx: 2
  num_reindex_processes: 2
  start_reindex_block: 1
  end_reindex_block: 5000000
  reindex: false

testnet:
  endpoints:
    ws: "ws://testnet.agent.axelarscan.io:26657"
    api: "https://testnet.api.axelarscan.io"
  num_prev_blocks_fetch_tx: 2
  num_reindex_processes: 2
  start_reindex_block: 690489
  end_reindex_block: 5000000
  reindex: false

devnet:
  endpoints:
    ws: "ws://devnet.agent.axelarscan.io:26657"
    api: "https://devnet.api.axelarscan.io"
  num_prev_blocks_fetch_tx: 0
  num_reindex_processes: 2
  start_reindex_block: 1
  end_reindex_block: 5000000
  reindex: false

testnet-2:
  endpoints:
    ws: "ws://testnet-2.agent.axelarscan.io:26657"
    api: "https://testnet-2.api.axelarscan.io"
  num_prev_blocks_fetch_tx: 1
  num_reindex_processes: 2
  start_reindex_block: 1
  end_reindex_block: 5000000
  reindex: false