version: '3.6'
services:
  axelarscan-agent:
    container_name: axelarscan-agent
    image: node:17.7.2-alpine
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_NO_WARNINGS=1
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/axelarscan-agent
      - node_modules:/usr/src/axelarscan-agent/node_modules
    networks:
      - axelarscan-agent
    command: npm run start
volumes:
  node_modules:
networks:
  axelarscan-agent:
    driver: bridge